### ISSUE TITLE
Add support for multiple element values

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ezid-client#20]
See http://dublincore.org/groups/kernel/spec/#anchor14

**Comment by grosscol** [comment]
I've just run into this using the datacite profile.  The spec for EZID might preclude the clients from doing this.

http://ezid.cdlib.org/doc/apidoc.html#request-response-bodies
> EZID's data model for metadata is a dictionary of element name/value pairs. The dictionary is single-valued: an element name may not be repeated.

**Comment by dchandekstark** [comment]
@grosscol Yeah, I'm not sure exactly how this should work across different profiles.  I haven't had a need for it myself, so this issue is really a placeholder documenting that ezid-client doesn't do it, what it is. :)

**Comment by dchandekstark** [comment]
@grosscol FWIW, v1.5.0, just released, raises an exception when trying to use an Array for a metadata value.
